// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJahaRiCJA70gj70HkO2DiS7WxL5rC3-4',
    appId: '1:955290131135:web:d7d0f6133c01d71b68440a',
    messagingSenderId: '955290131135',
    projectId: 'makemyhome-e5dbc',
    authDomain: 'makemyhome-e5dbc.firebaseapp.com',
    storageBucket: 'makemyhome-e5dbc.appspot.com',
    measurementId: 'G-36X2LHNHWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzSi2dlDDA2y0xQmvfPsKbbh6FxXGCKKc',
    appId: '1:955290131135:android:fadf8e59b84a9d8368440a',
    messagingSenderId: '955290131135',
    projectId: 'makemyhome-e5dbc',
    storageBucket: 'makemyhome-e5dbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJxzuWepqZBzgjo8zEomfFrnlsMkIHKc',
    appId: '1:955290131135:ios:6e17a50618c8ee8568440a',
    messagingSenderId: '955290131135',
    projectId: 'makemyhome-e5dbc',
    storageBucket: 'makemyhome-e5dbc.appspot.com',
    iosClientId: '955290131135-4m0hkfad4idl6naarppb2d15fdtjh8p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeyourhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcJxzuWepqZBzgjo8zEomfFrnlsMkIHKc',
    appId: '1:955290131135:ios:6e17a50618c8ee8568440a',
    messagingSenderId: '955290131135',
    projectId: 'makemyhome-e5dbc',
    storageBucket: 'makemyhome-e5dbc.appspot.com',
    iosClientId: '955290131135-4m0hkfad4idl6naarppb2d15fdtjh8p3.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeyourhome',
  );
}
